/**
 * SQL access for `backups` (migration 001). Mirrors
 * `platform/jobs/jobs.repository.ts`'s shape: one named method per row
 * transition, no hand-written SQL anywhere else in this module.
 *
 * `manifest` stores the exact JSON also written inside the archive itself
 * (`backup-archive.ts`) — `BackupSummary`'s `createdByLabel`,
 * `dmsImageDigest`, `mode` and `volumes` are all *derived* by parsing it
 * rather than duplicated into their own columns. The manifest is
 * self-describing by design (`@dwg/shared`'s `backups.ts`: "restorable by
 * hand… must be self-describing"), so parsing the one small JSON blob a
 * row already carries is simpler than a migration that would only repeat
 * data already there — unlike `jobs.created_by_label` (migration 004),
 * which earns its own column because `jobs` has no equivalent
 * self-describing payload to read it from.
 */
import type { Database } from '../../platform/db.js';
import {
  BackupManifestSchema,
  type BackupManifest,
  type BackupSummary,
  type BackupUploadStatus,
  type BackupVerificationStatus,
} from '@dwg/shared';

export interface BackupRow {
  readonly id: string;
  readonly created_at: string;
  readonly created_by_admin_id: string | null;
  readonly file_path: string;
  readonly size_bytes: number;
  readonly checksum: string;
  readonly manifest: string;
  readonly verification_status: string;
  readonly verified_at: string | null;
  // M13 — per-backup remote-upload state (migration 006).
  readonly upload_status: string;
  readonly upload_destination: string | null;
  readonly remote_key: string | null;
  readonly uploaded_at: string | null;
  readonly upload_error: string | null;
  readonly local_present: number;
}

function parseManifest(raw: string): BackupManifest {
  return BackupManifestSchema.parse(JSON.parse(raw));
}

function toSummary(row: BackupRow): BackupSummary {
  const manifest = parseManifest(row.manifest);
  return {
    id: row.id,
    createdAt: row.created_at,
    createdByAdminId: row.created_by_admin_id,
    createdByLabel: manifest.createdBy.label,
    mode: manifest.mode,
    sizeBytes: row.size_bytes,
    dmsImageDigest: manifest.dmsImageDigest,
    volumes: manifest.volumes.map((volume) => ({
      key: volume.key,
      entryCount: volume.entryCount,
      sizeBytes: volume.sizeBytes,
    })),
    verificationStatus: row.verification_status as BackupVerificationStatus,
    verifiedAt: row.verified_at,
    uploadStatus: row.upload_status as BackupUploadStatus,
    uploadDestination: row.upload_destination,
    uploadedAt: row.uploaded_at,
    uploadError: row.upload_error,
    localPresent: row.local_present !== 0,
  };
}

export interface InsertBackupParams {
  /** Generated by the caller (`generateId('bkp')`) *before* the archive itself is written — `backup-archive.ts` needs the id up front to name the output file. */
  readonly id: string;
  readonly createdByAdminId: string | null;
  readonly filePath: string;
  readonly sizeBytes: number;
  readonly checksum: string;
  readonly manifest: BackupManifest;
}

const DEFAULT_LIST_LIMIT = 100;

/** Upload failure summaries are display-only; cap the length so a verbose upstream error can't bloat the row. */
const MAX_UPLOAD_ERROR_LENGTH = 500;

export class BackupsRepository {
  constructor(private readonly db: Database) {}

  insert(params: InsertBackupParams): BackupSummary {
    this.db.run(
      `INSERT INTO backups
         (id, created_at, created_by_admin_id, file_path, size_bytes, checksum, manifest, verification_status, verified_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, 'unverified', NULL)`,
      [
        params.id,
        params.manifest.createdAt,
        params.createdByAdminId,
        params.filePath,
        params.sizeBytes,
        params.checksum,
        JSON.stringify(params.manifest),
      ],
    );
    return this.getSummaryByIdOrThrow(params.id);
  }

  getRowById(id: string): BackupRow | null {
    return this.db.get<BackupRow>('SELECT * FROM backups WHERE id = ?', [id]) ?? null;
  }

  getSummaryById(id: string): BackupSummary | null {
    const row = this.getRowById(id);
    return row ? toSummary(row) : null;
  }

  private getSummaryByIdOrThrow(id: string): BackupSummary {
    const summary = this.getSummaryById(id);
    if (!summary) {
      throw new Error(`BackupsRepository: backup ${id} was just inserted but cannot be read back`);
    }
    return summary;
  }

  getManifestById(id: string): BackupManifest | null {
    const row = this.getRowById(id);
    return row ? parseManifest(row.manifest) : null;
  }

  list(limit: number = DEFAULT_LIST_LIMIT): readonly BackupSummary[] {
    const rows = this.db.all<BackupRow>('SELECT * FROM backups ORDER BY created_at DESC LIMIT ?', [
      limit,
    ]);
    return rows.map(toSummary);
  }

  /** Most recent backup with `verification_status = 'verified'`, or `null` — the Tier 4 backup-gate fact shared by restore's pre-flight and the updates status endpoint (both ask "is there a safety net right now", not "is *this* backup verified"). */
  mostRecentVerified(): BackupSummary | null {
    const row = this.db.get<BackupRow>(
      `SELECT * FROM backups WHERE verification_status = 'verified' ORDER BY created_at DESC LIMIT 1`,
    );
    return row ? toSummary(row) : null;
  }

  markVerified(id: string, verifiedAt: string): BackupSummary {
    this.db.run(
      `UPDATE backups SET verification_status = 'verified', verified_at = ? WHERE id = ?`,
      [verifiedAt, id],
    );
    return this.getSummaryByIdOrThrow(id);
  }

  markVerificationFailed(id: string): BackupSummary {
    this.db.run(
      `UPDATE backups SET verification_status = 'failed', verified_at = NULL WHERE id = ?`,
      [id],
    );
    return this.getSummaryByIdOrThrow(id);
  }

  delete(id: string): void {
    this.db.run('DELETE FROM backups WHERE id = ?', [id]);
  }

  // -------------------------------------------------------------------------
  // M13 — remote-upload state transitions. Each is a single named UPDATE, so
  // the upload state machine's every move is auditable by reading this file.
  // -------------------------------------------------------------------------

  markUploading(id: string): void {
    this.db.run(
      `UPDATE backups SET upload_status = 'uploading', upload_error = NULL WHERE id = ?`,
      [id],
    );
  }

  /** Records a completed, remote-verified upload. Clears any prior error and stamps where/when it landed. */
  markUploaded(
    id: string,
    params: {
      readonly destination: string;
      readonly remoteKey: string;
      readonly uploadedAt: string;
    },
  ): void {
    this.db.run(
      `UPDATE backups
          SET upload_status = 'uploaded', upload_destination = ?, remote_key = ?, uploaded_at = ?, upload_error = NULL
        WHERE id = ?`,
      [params.destination, params.remoteKey, params.uploadedAt, id],
    );
  }

  /** Records a failed upload attempt. `errorMessage` is a safe summary only — callers never pass a signed URL or credential (see migration 006). */
  markUploadFailed(id: string, errorMessage: string): void {
    this.db.run(`UPDATE backups SET upload_status = 'failed', upload_error = ? WHERE id = ?`, [
      errorMessage.slice(0, MAX_UPLOAD_ERROR_LENGTH),
      id,
    ]);
  }

  /** Flags the local archive as reclaimed — called only after the remote copy is verified. The row remains, now describing a remote-only backup. */
  markLocalReclaimed(id: string): void {
    this.db.run('UPDATE backups SET local_present = 0 WHERE id = ?', [id]);
  }

  /** Backups that still hold a local archive and are awaiting (or retrying) upload — oldest first, the order a reconcile drains them. */
  listUploadCandidates(): readonly BackupRow[] {
    return this.db.all<BackupRow>(
      `SELECT * FROM backups
        WHERE upload_status IN ('pending', 'failed') AND local_present = 1
        ORDER BY created_at ASC`,
    );
  }

  /** Backups the panel believes are uploaded and remote-verified — newest first, the input to remote retention. */
  listUploaded(): readonly BackupRow[] {
    return this.db.all<BackupRow>(
      `SELECT * FROM backups WHERE upload_status = 'uploaded' ORDER BY created_at DESC`,
    );
  }
}
