import { ExternalLink, RefreshCw } from 'lucide-react';
import type { CertificateHealthState, TlsEndpointResult } from '@dwg/shared';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ErrorState } from '@/components/error-state';
import { PageHeader } from '@/components/page-header';
import { Skeleton } from '@/components/ui/skeleton';
import { StatusBadge } from '@/components/status/status-badge';
import type { Status } from '@/components/status/status';
import { ApiClientError, ApiError } from '@/lib/api-client';
import { formatDateTime } from '@/lib/format';
import { useTlsStatusQuery } from './use-security-queries';

const HEALTH_TO_STATUS: Readonly<Record<CertificateHealthState, Status>> = {
  healthy: 'healthy',
  warning: 'warning',
  critical: 'critical',
  unknown: 'unknown',
};

const SSL_TYPE_LABEL: Readonly<Record<string, string>> = {
  letsencrypt: "Let's Encrypt (external ACME client)",
  manual: 'Manually configured certificate',
  'self-signed': 'Self-signed (generated by docker-mailserver)',
  custom: 'Custom',
};

function EndpointCard({ endpoint }: { endpoint: TlsEndpointResult }) {
  return (
    <Card>
      <CardHeader className="flex-row items-center justify-between gap-2 space-y-0">
        <div>
          <CardTitle className="text-body font-semibold">{endpoint.label}</CardTitle>
          <p className="text-caption text-text-muted">Port {endpoint.port}</p>
        </div>
        <StatusBadge status={HEALTH_TO_STATUS[endpoint.health]} />
      </CardHeader>
      <CardContent className="flex flex-col gap-2 text-body-sm">
        {!endpoint.reachable || !endpoint.certificate ? (
          <p className="text-text-muted">
            {endpoint.error ?? 'Unknown — could not read a certificate.'}
          </p>
        ) : (
          <>
            <Row label="Subject" value={endpoint.certificate.subject} />
            <Row label="Issuer" value={endpoint.certificate.issuer} />
            <Row
              label="SANs"
              value={
                endpoint.certificate.subjectAltNames.length > 0
                  ? endpoint.certificate.subjectAltNames.join(', ')
                  : 'None'
              }
            />
            <Row label="Valid from" value={formatDateTime(endpoint.certificate.validFrom)} />
            <Row label="Valid to" value={formatDateTime(endpoint.certificate.validTo)} />
            <Row
              label="Days remaining"
              value={
                endpoint.certificate.daysRemaining < 0
                  ? `Expired ${Math.abs(endpoint.certificate.daysRemaining)} days ago`
                  : String(endpoint.certificate.daysRemaining)
              }
            />
            <Row label="Self-signed" value={endpoint.certificate.isSelfSigned ? 'Yes' : 'No'} />
          </>
        )}
      </CardContent>
    </Card>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-start justify-between gap-3">
      <span className="shrink-0 text-text-muted">{label}</span>
      <span className="text-right text-text-primary">{value}</span>
    </div>
  );
}

/**
 * `/security/tls` (FEATURE_MATRIX.md §12). Certificate status, issuer,
 * SANs, validity and expiry warnings for every DMS-default mail port.
 * **No issuance control anywhere on this page** — Let's Encrypt
 * certificates are consumed by DMS from an external ACME client, never
 * issued by this panel; the docs link is the closest this page ever gets
 * to that action.
 */
export function TlsPage() {
  const query = useTlsStatusQuery();

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="TLS Certificates"
        description="What each mail port actually presents, checked live. Warns at 30 days remaining, critical at 7."
        action={
          <Button
            type="button"
            variant="secondary"
            pending={query.isFetching}
            onClick={() => void query.refetch()}
          >
            <RefreshCw className="size-3.5" aria-hidden="true" />
            Re-check
          </Button>
        }
      />

      {query.isError ? (
        <ErrorState
          message="Could not check TLS status."
          errorId={
            query.error instanceof ApiError || query.error instanceof ApiClientError
              ? query.error.errorId
              : 'unknown'
          }
          onRetry={() => void query.refetch()}
        />
      ) : query.isLoading || !query.data ? (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {[0, 1, 2, 3, 4].map((i) => (
            <Skeleton key={i} className="h-48 w-full" />
          ))}
        </div>
      ) : (
        <>
          <Card>
            <CardContent className="flex flex-col gap-2 pt-4">
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div>
                  <p className="text-caption text-text-muted">SSL_TYPE</p>
                  <p className="text-body font-medium text-text-primary">
                    {query.data.sslType
                      ? (SSL_TYPE_LABEL[query.data.sslType] ?? query.data.sslType)
                      : 'Not set (no TLS configured)'}
                  </p>
                </div>
                <a
                  href={query.data.acmeDocsHref}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-1 text-body-sm text-accent underline-offset-2 hover:underline"
                >
                  Wiring an ACME client
                  <ExternalLink className="size-3.5" aria-hidden="true" />
                </a>
              </div>
              <p className="text-caption text-text-muted">
                docker-mailserver does not issue certificates — it consumes them from an external
                ACME client (certbot, Traefik, acme-companion). This panel shows status only.
              </p>
              <p className="text-caption text-text-muted">
                Last checked {formatDateTime(query.data.checkedAt)}
              </p>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            {query.data.endpoints.map((endpoint) => (
              <EndpointCard key={endpoint.protocol} endpoint={endpoint} />
            ))}
          </div>
        </>
      )}
    </div>
  );
}
